iimage:
  repository: 929897439921.dkr.ecr.us-east-1.amazonaws.com/netflix-clone
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred
  
service:
  type: LoadBalancer
  port: 80

