apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato-clone
  template:
    metadata:
      labels:
        app: zomato-clone
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 3000
    # spec:
    #   containers:
    #     - name: netflix
    #       image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    #       ports:
    #         - containerPort: 3000
      # {{- if .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      # {{- end }}
      # containers:
      #   - name: netflix
      #     image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      #     ports:
      #       - containerPort: 3000