apiVersion: v1
kind: Service
metadata:
  name: zomato-clone
spec:
  type: {{ .Values.service.type }}
  selector:
    app: zomato-clone
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000