name: CI-CD Build & Deploy with ArgoCD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -input=false

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: 929897439921.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: netflix-clone
        IMAGE_TAG: latest
      run: |
        cd app_code
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name netflix-cluster --region us-east-1

    - name: Ensure ArgoCD namespace exists
      run: |
        kubectl get ns argocd || kubectl create ns argocd

    - name: Wait for ArgoCD server pod to be ready
      run: |
        echo "Waiting for ArgoCD server pod to be ready..."
        for i in {1..10}; do
          STATUS=$(kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o jsonpath='{.items[0].status.phase}')
          READY=$(kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
          echo "Status: $STATUS, Ready: $READY"
          if [ "$STATUS" = "Running" ] && [ "$READY" = "true" ]; then
            echo "ArgoCD server is ready."
            break
          fi
          echo "Waiting 15 seconds..."
          sleep 15
        done
    

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd

    - name: Login to ArgoCD CLI
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER_IP }} \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure
        TOKEN=$(argocd account generate-token)
        echo "::add-mask::$TOKEN"
        echo "ARGOCD_TOKEN=$TOKEN" >> $GITHUB_ENV
  

    - name: Create SSH repo secret in ArgoCD
      run: |
        echo "${{ secrets.ARGOCD_SSH_PRIVATE_KEY }}" > id_rsa
        kubectl create secret generic github-ssh-creds \
          --namespace argocd \
          --from-literal=url=git@github.com:Jyo-Patil/Zomato_deployment.git \
          --from-file=sshPrivateKey=id_rsa \
          --type Opaque \
          --dry-run=client -o yaml | \
        kubectl label --local -f - \
          argocd.argoproj.io/secret-type=repository -o yaml | \
        kubectl apply -f -
        rm id_rsa

    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f argocd/netflix-clone-app.yaml -n argocd

    - name: Sync ArgoCD Application using Token
      run: |
         argocd app sync netflix-clone \
         --grpc-web \
         --auth-token ${{ env.ARGOCD_TOKEN }}




    # - name: Update kubeconfig for EKS
    #   run: |
    #     aws eks update-kubeconfig --name netflix-cluster --region us-east-1

    # - name: Ensure ArgoCD is installed
    #   run: |
    #     kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    #     echo "Waiting for ArgoCD server deployment to be ready..."
    #     sleep 30
    #     kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd

    # - name: Deploy ArgoCD Application resource
    #   run: |
    #     kubectl apply -f argocd/netflix-clone-app.yaml -n argocd

    # - name: Install ArgoCD CLI
    #   run: |
    #     curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    #     chmod +x /usr/local/bin/argocd

    # - name: Login to ArgoCD
    #   run: |
    #     argocd login 52.91.70.212:30335 \
    #       --username admin \
    #       --password ${{ secrets.ARGOCD_PASSWORD }} \
    #       --insecure

    # - name: Sync ArgoCD Application
    #   run: |
    #     argocd app sync netflix-clone --grpc-web